/**
 * MINIMAL LAYOUT for deployed sites
 * 
 * This layout just passes through children - the parent RootLayout still wraps this,
 * but the Navbar, Breadcrumbs, and Footer will hide themselves based on the route.
 * 
 * Metadata is generated by the page.tsx using generateMetadata.
 */
export default function SiteViewLayout({ children }: { children: React.ReactNode }) {
    return children;
}
