ALTER TABLE conversations 
ADD COLUMN IF NOT EXISTS is_group BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS name TEXT,
ADD COLUMN IF NOT EXISTS group_image TEXT,
ADD COLUMN IF NOT EXISTS owner_id UUID REFERENCES auth.users(id);
